/**
 * 静态 CSS 文件生成脚本
 * 
 * 此脚本为每个 Tokyo Night 主题变体生成静态 CSS 文件：
 * - theme-night.css (Night 变体)
 * - theme-storm.css (Storm 变体) 
 * - theme-light.css (Light 变体)
 * 
 * 生成的文件将放置在 public 目录中，供 Orca 主题系统使用。
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// 获取当前文件的目录路径
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');
const publicDir = join(projectRoot, 'public');

// 由于 TypeScript 编译问题，我们直接在这里定义需要的类型和函数
type ThemeVariant = 'night' | 'storm' | 'light';

// Tokyo Night 颜色定义
const colorVariants = {
  night: {
    background: {
      primary: '#1a1b26',
      secondary: '#16161e',
      tertiary: '#24283b',
    },
    text: {
      primary: '#a9b1d6',
      secondary: '#9aa5ce',
      muted: '#565f89',
    },
    semantic: {
      red: '#f7768e',
      orange: '#ff9e64',
      yellow: '#e0af68',
      green: '#9ece6a',
      cyan: '#7dcfff',
      blue: '#7aa2f7',
      purple: '#bb9af7',
    },
    ui: {
      border: '#292e42',
      hover: '#414868',
      selection: '#364a82',
      focus: '#7aa2f7',
    }
  },
  storm: {
    background: {
      primary: '#24283b',
      secondary: '#1f2335',
      tertiary: '#292e42',
    },
    text: {
      primary: '#a9b1d6',
      secondary: '#9aa5ce',
      muted: '#565f89',
    },
    semantic: {
      red: '#f7768e',
      orange: '#ff9e64',
      yellow: '#e0af68',
      green: '#9ece6a',
      cyan: '#7dcfff',
      blue: '#7aa2f7',
      purple: '#bb9af7',
    },
    ui: {
      border: '#3b4261',
      hover: '#4a5374',
      selection: '#3d59a1',
      focus: '#7aa2f7',
    }
  },
  light: {
    background: {
      primary: '#d5d6db',
      secondary: '#e9e9ed',
      tertiary: '#ffffff',
    },
    text: {
      primary: '#343b58',
      secondary: '#4f5b93',
      muted: '#6c7394',
    },
    semantic: {
      red: '#8c4351',
      orange: '#965027',
      yellow: '#8f5e15',
      green: '#485e30',
      cyan: '#166775',
      blue: '#34548a',
      purple: '#5a4a78',
    },
    ui: {
      border: '#c4c8da',
      hover: '#b6bbd9',
      selection: '#a8aed6',
      focus: '#34548a',
    }
  }
};

/**
 * 生成 CSS 自定义属性字符串
 */
function generateCSSCustomProperties(variant: ThemeVariant): string {
  const colors = colorVariants[variant];
  
  return `
  /* Tokyo Night ${variant} 变体的自定义属性 */
  --tokyo-night-bg-primary: ${colors.background.primary};
  --tokyo-night-bg-secondary: ${colors.background.secondary};
  --tokyo-night-bg-tertiary: ${colors.background.tertiary};
  
  --tokyo-night-text-primary: ${colors.text.primary};
  --tokyo-night-text-secondary: ${colors.text.secondary};
  --tokyo-night-text-muted: ${colors.text.muted};
  
  --tokyo-night-red: ${colors.semantic.red};
  --tokyo-night-orange: ${colors.semantic.orange};
  --tokyo-night-yellow: ${colors.semantic.yellow};
  --tokyo-night-green: ${colors.semantic.green};
  --tokyo-night-cyan: ${colors.semantic.cyan};
  --tokyo-night-blue: ${colors.semantic.blue};
  --tokyo-night-purple: ${colors.semantic.purple};
  
  --tokyo-night-border: ${colors.ui.border};
  --tokyo-night-hover: ${colors.ui.hover};
  --tokyo-night-selection: ${colors.ui.selection};
  --tokyo-night-focus: ${colors.ui.focus};`;
}

/**
 * 生成 Orca 颜色映射
 */
function generateOrcaColorMapping(variant: ThemeVariant): string {
  const colors = colorVariants[variant];
  
  return `
    /* Orca 变量覆盖，使用 Tokyo Night 颜色 */
    --orca-color-bg-0: ${colors.background.primary};
    --orca-color-bg-1: ${colors.background.secondary};
    --orca-color-bg-2: ${colors.background.tertiary};
    
    --orca-color-text-0: ${colors.text.primary};
    --orca-color-text-1: ${colors.text.secondary};
    --orca-color-text-2: ${colors.text.muted};
    
    --orca-color-primary-5: ${colors.semantic.blue};
    --orca-color-success-5: ${colors.semantic.green};
    --orca-color-warn-5: ${colors.semantic.orange};
    --orca-color-dangerous-5: ${colors.semantic.red};
    --orca-color-info-5: ${colors.semantic.cyan};
    
    --orca-color-border: ${colors.ui.border};
    --orca-color-hover: ${colors.ui.hover};
    --orca-color-selection: ${colors.ui.selection};`;
}

/**
 * 为指定变体生成完整的静态 CSS 内容
 */
function generateVariantCSS(variant: ThemeVariant): string {
  console.log(`正在生成 ${variant} 变体的 CSS...`);
  
  const customProperties = generateCSSCustomProperties(variant);
  const orcaMapping = generateOrcaColorMapping(variant);
  
  const fullCSS = `/*
 * Tokyo Night Theme - ${variant.charAt(0).toUpperCase() + variant.slice(1)} Variant
 * 
 * 此文件由构建脚本自动生成，请勿手动编辑。
 * Generated by: scripts/generateStaticCSS.ts
 * Variant: ${variant}
 * Generated at: ${new Date().toISOString()}
 */

:root {${customProperties}
${orcaMapping}
}

/* ========== 基础样式 ========== */

/* 编辑器区域 - 最高视觉优先级 */
.orca-editor,
.orca-note-editor,
.orca-markdown-editor {
    background-color: var(--tokyo-night-bg-primary) !important;
    color: var(--tokyo-night-text-primary) !important;
    /* 确保编辑器具有最高的视觉权重 */
    position: relative;
    z-index: 1;
}

/* 侧边栏 - 降低视觉权重 */
nav#sidebar,
.orca-sidebar {
    background-color: var(--tokyo-night-bg-secondary) !important;
    color: var(--tokyo-night-text-secondary) !important;
    border-right: 1px solid var(--tokyo-night-border) !important;
    /* 减少侧边栏的视觉突出度 */
    opacity: 0.95;
    box-shadow: none !important;
}

/* 侧边栏项目的悬停效果 */
nav#sidebar .orca-sidebar-item:hover,
.orca-sidebar .orca-sidebar-item:hover {
    background-color: var(--tokyo-night-hover) !important;
    color: var(--tokyo-night-text-primary) !important;
    /* 微妙的悬停反馈 */
    transition: all 0.2s ease;
}

/* 侧边栏选中项目 */
nav#sidebar .orca-sidebar-item.selected,
.orca-sidebar .orca-sidebar-item.selected {
    background-color: var(--tokyo-night-selection) !important;
    color: var(--tokyo-night-text-primary) !important;
    border-left: 3px solid var(--tokyo-night-blue) !important;
}

/* ========== UI 组件样式 ========== */

/* 按钮样式 */
.orca-button {
    border-radius: 6px !important;
    font-weight: 500 !important;
    transition: all 0.2s ease !important;
}

.orca-button.primary {
    background-color: var(--tokyo-night-blue) !important;
    color: var(--tokyo-night-bg-primary) !important;
    border-color: var(--tokyo-night-blue) !important;
}

.orca-button.primary:hover {
    filter: brightness(1.1) !important;
    transform: translateY(-1px) !important;
    box-shadow: 0 2px 8px var(--tokyo-night-blue)44 !important;
}

/* 输入框样式 */
.orca-input,
.orca-textarea {
    background-color: var(--tokyo-night-bg-primary) !important;
    border: 1px solid var(--tokyo-night-border) !important;
    border-radius: 6px !important;
    color: var(--tokyo-night-text-primary) !important;
    transition: border-color 0.2s ease, box-shadow 0.2s ease !important;
}

.orca-input:focus,
.orca-textarea:focus {
    border-color: var(--tokyo-night-focus) !important;
    box-shadow: 0 0 0 2px var(--tokyo-night-focus)33 !important;
    outline: none !important;
}

/* 模态框样式 */
.orca-modal {
    background-color: var(--tokyo-night-bg-tertiary) !important;
    color: var(--tokyo-night-text-primary) !important;
    border: 1px solid var(--tokyo-night-border) !important;
    border-radius: 8px !important;
    box-shadow: 0 12px 32px rgba(0,0,0,0.4) !important;
}

/* 表格样式 */
.orca-table {
    background-color: var(--tokyo-night-bg-primary) !important;
    border: 1px solid var(--tokyo-night-border) !important;
    border-radius: 6px !important;
}

.orca-table-header {
    background-color: var(--tokyo-night-bg-secondary) !important;
    color: var(--tokyo-night-text-primary) !important;
    border-bottom: 1px solid var(--tokyo-night-border) !important;
    font-weight: 600 !important;
}

.orca-table-row:hover {
    background-color: var(--tokyo-night-hover) !important;
}

/* ========== 语义颜色应用 ========== */

/* 错误状态 */
.orca-error,
.error {
    color: var(--tokyo-night-red) !important;
    border-color: var(--tokyo-night-red) !important;
}

/* 成功状态 */
.orca-success,
.success {
    color: var(--tokyo-night-green) !important;
    border-color: var(--tokyo-night-green) !important;
}

/* 警告状态 */
.orca-warning,
.warning {
    color: var(--tokyo-night-orange) !important;
    border-color: var(--tokyo-night-orange) !important;
}

/* 信息状态 */
.orca-info,
.info {
    color: var(--tokyo-night-cyan) !important;
    border-color: var(--tokyo-night-cyan) !important;
}

/* ========== 排版增强 ========== */

/* 代码块 */
code,
.orca-code {
    background-color: var(--tokyo-night-bg-secondary) !important;
    color: var(--tokyo-night-text-primary) !important;
    border: 1px solid var(--tokyo-night-border) !important;
    border-radius: 4px !important;
    padding: 0.2em 0.4em !important;
    font-family: 'Fira Code', 'Monaco', 'Consolas', monospace !important;
}

/* 链接 */
a,
.orca-link {
    color: var(--tokyo-night-blue) !important;
    text-decoration: none !important;
    transition: color 0.2s ease !important;
}

a:hover,
.orca-link:hover {
    color: var(--tokyo-night-cyan) !important;
    text-decoration: underline !important;
}

/* ========== 动画和过渡 ========== */

/* 全局过渡效果 */
* {
    transition-duration: 0.2s !important;
    transition-timing-function: ease !important;
}

/* 焦点指示器 */
*:focus-visible {
    outline: 2px solid var(--tokyo-night-focus) !important;
    outline-offset: 2px !important;
    border-radius: 4px !important;
}

/* ========== 响应式设计 ========== */

@media (max-width: 768px) {
    /* 移动设备上的样式调整 */
    nav#sidebar,
    .orca-sidebar {
        opacity: 0.9 !important;
    }
}

/* ========== 可访问性增强 ========== */

@media (prefers-contrast: high) {
    :root {
        --tokyo-night-border: ${variant === 'light' ? '#999999' : '#555555'} !important;
    }
}

@media (prefers-reduced-motion: reduce) {
    * {
        animation-duration: 0.01ms !important;
        animation-iteration-count: 1 !important;
        transition-duration: 0.01ms !important;
    }
}

/* ========== 变体特定标识 ========== */

body[data-theme-variant="${variant}"] {
    /* 变体标识符，用于调试和特定样式 */
}
`;

  return fullCSS;
}

/**
 * 将 CSS 内容写入文件
 */
function writeVariantCSSFile(variant: ThemeVariant, cssContent: string): void {
  const fileName = `theme-${variant}.css`;
  const filePath = join(publicDir, fileName);
  
  try {
    // 确保 public 目录存在
    if (!existsSync(publicDir)) {
      mkdirSync(publicDir, { recursive: true });
    }
    
    // 写入 CSS 文件
    writeFileSync(filePath, cssContent, 'utf8');
    console.log(`✅ 成功生成: ${fileName}`);
  } catch (error) {
    console.error(`❌ 写入 ${fileName} 失败:`, error);
    throw error;
  }
}

/**
 * 生成所有变体的静态 CSS 文件
 */
function generateAllVariantCSS(): void {
  console.log('🎨 开始生成 Tokyo Night 主题的静态 CSS 文件...\n');
  
  const variants: ThemeVariant[] = ['night', 'storm', 'light'];
  
  let successCount = 0;
  let errorCount = 0;
  
  for (const variant of variants) {
    try {
      const cssContent = generateVariantCSS(variant);
      writeVariantCSSFile(variant, cssContent);
      successCount++;
    } catch (error) {
      console.error(`❌ 处理 ${variant} 变体时出错:`, error);
      errorCount++;
    }
  }
  
  console.log('\n📊 生成结果:');
  console.log(`✅ 成功: ${successCount} 个文件`);
  console.log(`❌ 失败: ${errorCount} 个文件`);
  
  if (errorCount > 0) {
    console.error('\n❌ 部分文件生成失败，请检查错误信息');
    process.exit(1);
  } else {
    console.log('\n🎉 所有静态 CSS 文件生成完成！');
  }
}

/**
 * 验证生成的 CSS 文件
 */
function validateGeneratedFiles(): void {
  console.log('\n🔍 验证生成的 CSS 文件...');
  
  const variants: ThemeVariant[] = ['night', 'storm', 'light'];
  let validationErrors = 0;
  
  for (const variant of variants) {
    const fileName = `theme-${variant}.css`;
    const filePath = join(publicDir, fileName);
    
    if (!existsSync(filePath)) {
      console.error(`❌ 文件不存在: ${fileName}`);
      validationErrors++;
      continue;
    }
    
    try {
      const content = readFileSync(filePath, 'utf8');
      
      // 基本验证：检查文件是否包含必要的内容
      const requiredPatterns = [
        /Tokyo Night Theme/,
        /--tokyo-night-/,
        /:root/,
        new RegExp(`${variant}`, 'i')
      ];
      
      for (const pattern of requiredPatterns) {
        if (!pattern.test(content)) {
          console.error(`❌ ${fileName} 缺少必要内容: ${pattern}`);
          validationErrors++;
        }
      }
      
      console.log(`✅ ${fileName} 验证通过`);
    } catch (error) {
      console.error(`❌ 读取 ${fileName} 时出错:`, error);
      validationErrors++;
    }
  }
  
  if (validationErrors > 0) {
    console.error(`\n❌ 验证失败，发现 ${validationErrors} 个错误`);
    process.exit(1);
  } else {
    console.log('\n✅ 所有文件验证通过！');
  }
}

// 主执行逻辑
if (process.argv[1] && process.argv[1].includes('generateStaticCSS')) {
  try {
    generateAllVariantCSS();
    validateGeneratedFiles();
  } catch (error) {
    console.error('❌ 脚本执行失败:', error);
    process.exit(1);
  }
}

// 导出函数供测试使用
export {
  generateVariantCSS,
  writeVariantCSSFile,
  generateAllVariantCSS,
  validateGeneratedFiles
};